//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayRoutings.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class t__departments
    {
        public int id { get; set; }
        [DisplayName("Departamento")]
        public string department_pt { get; set; }
        public string department_en { get; set; }
        public string department_de { get; set; }
        public Nullable<int> pcs_enabled { get; set; }
        public Nullable<int> das_enabled { get; set; }
        public Nullable<int> hbc_enabled { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public Nullable<int> insert_author { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_author { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> sort_order { get; set; }
        public Nullable<int> director_id { get; set; }
        public string director_cc { get; set; }
        public string ProductFilter { get; set; }
    }
}
