//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayRoutings.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class t__users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t__users()
        {
            this.vw_holiday_routings = new HashSet<vw_holiday_routings>();
            this.vw_holiday_routings1 = new HashSet<vw_holiday_routings>();
        }

        public int id { get; set; }
        public string user_logon { get; set; }
        public string user_pass { get; set; }
        public string user_pass_temp { get; set; }
        [DisplayName("Nome")]
        public string user_name { get; set; }
        [DisplayName("Função")]
        public string user_alias { get; set; }
        [DisplayName("Função PT")]
        public string user_alias_pt { get; set; }
        [DisplayName("Função EN")]
        public string user_alias_en { get; set; }
        public string user_alias_de { get; set; }
        [DisplayName("Título PT")]
        public string user_title_pt { get; set; }
        [DisplayName("Título EN")]
        public string user_title_en { get; set; }
        public string user_title_de { get; set; }
        [DisplayName("Email")]
        public string user_email { get; set; }
        public string user_pc_name { get; set; }
        [DisplayName("Telefone")]
        public Nullable<int> user_phone_ext { get; set; }
        public string user_phone_1 { get; set; }
        public string user_phone_2 { get; set; }
        public string user_phone_3 { get; set; }
        public string user_phone_4 { get; set; }
        public string user_phone_5 { get; set; }
        public string user_lang { get; set; }
        public string user_gender { get; set; }
        public Nullable<int> dep_id { get; set; }
        public Nullable<int> comp_id { get; set; }
        public Nullable<int> toner_requests { get; set; }
        public Nullable<double> valor_hora { get; set; }
        public Nullable<double> valor_hora_custo { get; set; }
        public Nullable<int> pcs_enabled { get; set; }
        public Nullable<int> pcs_user_level { get; set; }
        public Nullable<int> pcs_results_per_page { get; set; }
        public Nullable<int> hbc_enabled { get; set; }
        public Nullable<int> hbc_user_id { get; set; }
        public Nullable<int> hbc_user_level { get; set; }
        public string hbc_routing { get; set; }
        public string hbc_check_users { get; set; }
        public Nullable<int> hbc_results_per_page { get; set; }
        public Nullable<int> mas_enabled { get; set; }
        public Nullable<int> mas_user_level { get; set; }
        public Nullable<int> mas_results_per_page { get; set; }
        public Nullable<int> dil_enabled { get; set; }
        public Nullable<int> dil_user_level { get; set; }
        public Nullable<int> dil_results_per_page { get; set; }
        public string dil_language { get; set; }
        public string dil_permissions { get; set; }
        public Nullable<int> wcm_enabled { get; set; }
        public Nullable<int> wcm_user_level { get; set; }
        public Nullable<int> wcm_results_per_page { get; set; }
        public string wcm_editable_pages { get; set; }
        public Nullable<int> vcs_enabled { get; set; }
        public Nullable<int> vcs_user_level { get; set; }
        public Nullable<int> vcs_results_per_page { get; set; }
        public Nullable<int> tas_enabled { get; set; }
        public Nullable<int> tas_user_level { get; set; }
        public Nullable<int> tas_results_per_page { get; set; }
        public Nullable<int> oe_enabled { get; set; }
        public Nullable<int> ir_oe_user_level { get; set; }
        public Nullable<int> ir_oe_enabled { get; set; }
        public Nullable<int> ir_oe_results_per_page { get; set; }
        public Nullable<int> ppr_print { get; set; }
        public Nullable<int> ppr_level { get; set; }
        public Nullable<int> bdg_enabled { get; set; }
        public Nullable<int> bdg_user_level { get; set; }
        public Nullable<int> prop_enabled { get; set; }
        public Nullable<int> pcr_enabled { get; set; }
        public Nullable<int> evc_dep_enabled { get; set; }
        public Nullable<int> gir_enabled { get; set; }
        public Nullable<int> rhhe_comp_id { get; set; }
        public Nullable<int> rhhe_enabled { get; set; }
        public Nullable<int> rhhe_user_id { get; set; }
        public Nullable<int> isa_enabled { get; set; }
        public Nullable<int> isa_user_level { get; set; }
        public Nullable<int> isa_results_per_page { get; set; }
        public string isa_language { get; set; }
        public Nullable<int> ecf_enabled { get; set; }
        public Nullable<int> ecf_user_level { get; set; }
        public string ecf_commisions { get; set; }
        public string VendorNo { get; set; }
        public Nullable<int> villalist_enabled { get; set; }
        public Nullable<int> villalist_user_level { get; set; }
        public Nullable<int> rca_enabled { get; set; }
        public Nullable<int> rca_user_level { get; set; }
        public string rca_dep { get; set; }
        public Nullable<int> hsk_app_enabled { get; set; }
        public Nullable<int> hsk_app_user_level { get; set; }
        public Nullable<int> prs_enabled { get; set; }
        public Nullable<int> prs_user_level { get; set; }
        public Nullable<int> cms_enabled { get; set; }
        public Nullable<int> cms_user_level { get; set; }
        public Nullable<int> addressbook { get; set; }
        public Nullable<System.DateTime> login_date { get; set; }
        public string login_ip { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string insert_author { get; set; }
        public string update_date { get; set; }
        public string update_author { get; set; }
        [DisplayName("Activo")]
        public Nullable<int> status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vw_holiday_routings> vw_holiday_routings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vw_holiday_routings> vw_holiday_routings1 { get; set; }
        public virtual t__companies t__companies { get; set; }
        public virtual t__departments t__departments { get; set; }
    }
}
