//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayRoutings.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web.Mvc;

    public partial class vl_HRC_HBC_HOLIDAY_DEPARTMENT_ROUTING
    {
        [Display(Name = "Colaborador")]
        public int user_id { get; set; }
        [Display(Name = "Responsável")]
        public int person_in_charge_id { get; set; }
        [Display(Name = "Obrigatório")]
        public Nullable<int> mandatory { get; set; }

        public IEnumerable<SelectListItem> OptionList
        {
            get
            {
                List<SelectListItem> list = new List<SelectListItem> {
                        new SelectListItem() {
                            Text = "Sim", Value = "1"
                        },
                        new SelectListItem() {
                            Text = "Não", Value = "0"
                        }
                    };
                return list.Select(l => new SelectListItem { Selected = (l.Value == mandatory.ToString()), Text = l.Text, Value = l.Value });
            }
        }
        public string user_name { get; set; }
        public string person_in_charge_name { get; set; }
    }
}
