//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayRoutings.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.Web.Mvc;

    public partial class vl_HRC_HBC_ASSIGNED_HOLIDAYS
    {
        public int id { get; set; }
        [DisplayName("Ano")]
        public int year_related { get; set; }
        [DisplayName("Total Dias")]
        public Nullable<double> total_days { get; set; }
        [DisplayName("Dias Bónus")]
        public Nullable<double> bonus_days { get; set; }
        [DisplayName("Fins de Semana")]
        public Nullable<int> weekends_allowed { get; set; }
        [DisplayName("Meias Sextas-Feiras")]
        public Nullable<int> half_fridays { get; set; }
        [DisplayName("Primeiro Ano")]
        public Nullable<int> first_year { get; set; }

        public IEnumerable<SelectListItem> weekendsList
        {
            get
            {
                List<SelectListItem> list = new List<SelectListItem> {
                        new SelectListItem() {
                            Text = "Sim", Value = "1"
                        },
                        new SelectListItem() {
                            Text = "Não", Value = "0"
                        }
                    };
                return list.Select(l => new SelectListItem { Selected = (l.Value == weekends_allowed.ToString()), Text = l.Text, Value = l.Value });
            }
        }

        public IEnumerable<SelectListItem> fridaysList
        {
            get
            {
                List<SelectListItem> list = new List<SelectListItem> {
                        new SelectListItem() {
                            Text = "Sim", Value = "1"
                        },
                        new SelectListItem() {
                            Text = "Não", Value = "0"
                        }
                    };
                return list.Select(l => new SelectListItem { Selected = (l.Value == half_fridays.ToString()), Text = l.Text, Value = l.Value });
            }
        }

        public IEnumerable<SelectListItem> yearsList
        {
            get
            {
                List<SelectListItem> list = new List<SelectListItem> {
                        new SelectListItem() {
                            Text = "Sim", Value = "1"
                        },
                        new SelectListItem() {
                            Text = "Não", Value = "0"
                        }
                    };
                return list.Select(l => new SelectListItem { Selected = (l.Value == first_year.ToString()), Text = l.Text, Value = l.Value });
            }
        }
    }
}
